name: self_driving
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - numpy
    - glob
    - matplotlib
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - opencv-python
    - pillow
    - pip:
        - pygame
        - tensorflow-gpu==1.12
        - keras==2.24